---
- name: apt upgrade
  hosts: all
  tags:
    - apt_upgrade
  become: true
  tasks:
    - apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

- name: Création des compte des administrateurs
  hosts: all
  tags:
    - admins
  become: True
  tasks:
    - include_role:
        name: nickjj.user
      loop: "{{admins}}"
      vars:
        user_name: "{{item}}"

- name: Importation des clés des administrateurs
  hosts: all
  tags:
    - public_keys
  tasks:
    - become: yes
      authorized_key:
        user: "{{item}}"
        state: present
        key: "https://github.com/{{item}}.keys"
      loop: "{{admins}}"

#- name: Installation de pip
#  hosts: all
#  become: yes
#  vars:
#    pip_package: python3-pip
#    pip_executable: pip3
#  tags:
#    - install-pip
#  tasks:
#    - include_role:
#        name: geerlingguy.pip

- name: Installation de Docker et docker-compose
  hosts: all
  become: yes
  vars:
    docker_install_compose: true
  tags:
    - install-docker
  tasks:
    - include_role:
        name: geerlingguy.docker

#- name: Install docker-py
#  hosts: all
#  tags:
#    - install-docker-python
#  tasks:
#    - pip:
#        name: docker
#        executable: pip3
#      become: yes

- name: Configuration du hostname du serveur
  hosts: all
  become: yes
  tags:
    - config-hostname
  tasks:
    - include_role:
        name: ypsman.hostname

- name: Création du compte rocket.chat
  hosts: all
  become: yes
  tags:
    - install-rocketchat
  tasks:
    - user:
        name: rocketchat
        #password: '???'
        groups:
          - docker
          - sudo
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/rocketchat

- name: Préparation de l'installation de rocket.chat
  hosts: all
  tags:
    - install-rocketchat
  tasks:
    - name: Ajout de l'adresse de rocket.chat dans /etc/hosts
      become: yes
      blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1 {{adresse_rocketchat}}
    - name: Création des répertoires pour rocket.chat
      become: yes
      file:
        path: /var/www/rocket.chat/data/runtime/db
        state: directory
        owner: rocketchat
        group: rocketchat
        mode: '0644'
      file:
        path: /var/www/rocket.chat/data/dump
        state: directory
        owner: rocketchat
        group: rocketchat
        mode: '0644'
    - name: copie du docker-compose.yml
      become: yes
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: /home/rocketchat/docker-compose.yml
        owner: rocketchat
        group: rocketchat
        mode: '0644'
    - name: Build et démarrage
      become: yes
      become_user: rocketchat
      ansible.builtin.shell: cd ~ ; docker-compose up -d
