---
- name: "Création d'un utilisateur"
  hosts: all
  become: True
  tasks:
    - include_role:
        name: nickjj.user
      loop: "{{admins}}"
      vars:
        user_name: "{{item}}"

# tasks file for ansible-dravedev-developers-ssh
- name: Set up multiple authorized keys
  hosts: all
  #become: yes
  tags:
    - public_keys
  tasks:
    - become: yes
      #become_user: "{{item}}"
      authorized_key:
        user: "{{item}}"
        state: present
        key: "https://github.com/{{item}}.keys"
      loop: "{{admins}}"

- name: Installation de Docker et docker-compose
  hosts: all
  become: yes
  vars:
    docker_install_compose: true
  tags:
    - install-docker
  tasks:
    - include_role:
        name: geerlingguy.docker
