---
- name: "Création des utilisateurs"
  hosts: all
  become: True
  tasks:
    - name: Utilisation du role nickjj.user
      include_role:
        name: nickjj.user
      loop: "{{admins}}"
      vars:
        user_name: "{{item}}"

# tasks file for ansible-dravedev-developers-ssh
- name: Set up multiple authorized keys
  hosts: all
  #become: yes
  tags:
    - public_keys
  tasks:
    - name: Ajout des utilisateurs
      become: yes
      #become_user: "{{item}}"
      authorized_key:
        user: "{{item}}"
        state: present
        key: "https://github.com/{{item}}.keys"
      loop: "{{admins}}"

# Configuration du pare-feu
- name: Pare-feu
  hosts: all
  become: True
  tasks:
    - name: Utilisation du role weareinteractive.ufw
      include_role:
        name: weareinteractive.ufw
      loop: "{{ports}}"
      vars:
        to_port: "{{item}}"

- name: Ouverture des ports
  hosts: all
  #become: yes
  tags:
    - pare-feu
  tasks:
    - name: blabla
      become: yes
      ufw_rules:
      - rule: allow
        to_port: "{{item}}"
        protocol: tcp
        comment: 'ouverture du port "{{item}}"'
      loop: "{{ports}}"
