---
- name: Création des administrateurs
  hosts: all
  become: True
  tasks:
    - include_role:
        name: nickjj.user
      loop: "{{admins}}"
      vars:
        user_name: "{{item}}"

- name: Importation des clés des administrateurs
  hosts: all
  tags:
    - public_keys
  tasks:
    - become: yes
      authorized_key:
        user: "{{item}}"
        state: present
        key: "https://github.com/{{item}}.keys"
      loop: "{{admins}}"

- name: Installation de pip
  hosts: all
  become: yes
  vars:
    pip_package: python3-pip
    pip_executable: pip3
  tags:
    - install-pip
  tasks:
    - include_role:
        name: geerlingguy.pip

- name: Installation de Docker et docker-compose
  hosts: all
  become: yes
  vars:
    docker_install_compose: true
  tags:
    - install-docker
  tasks:
    - include_role:
        name: geerlingguy.docker

- name: Configuration du hostname du serveur
  hosts: all
  become: yes
  tags:
    - config-hostname
  tasks:
    - include_role:
        name: ypsman.hostname
