---
- name: Création des administrateurs
  hosts: all
  become: True
  tasks:
    - include_role:
        name: nickjj.user
      loop: "{{admins}}"
      vars:
        user_name: "{{item}}"

- name: Importation des clés des administrateurs
  hosts: all
  tags:
    - public_keys
  tasks:
    - become: yes
      authorized_key:
        user: "{{item}}"
        state: present
        key: "https://github.com/{{item}}.keys"
      loop: "{{admins}}"

- name: Installation de pip
  hosts: all
  become: yes
  vars:
    pip_package: python3-pip
    pip_executable: pip3
  tags:
    - install-pip
  tasks:
    - include_role:
        name: geerlingguy.pip

- name: Installation de Docker et docker-compose
  hosts: all
  become: yes
  vars:
    docker_install_compose: true
  tags:
    - install-docker
  tasks:
    - include_role:
        name: geerlingguy.docker

#- name: Install docker-py
#  hosts: all
#  tags:
#    - install-docker-python
#  tasks:
#    - pip:
#        name: docker
#        executable: pip3
#      become: yes

- name: Configuration du hostname du serveur
  hosts: all
  become: yes
  tags:
    - config-hostname
  tasks:
    - include_role:
        name: ypsman.hostname

- name: ajout de l'adresse de rocket.chat dans /etc/hosts
  hosts: all
  become: yes
  tags:
    - adresse-rocketchat
  tasks:
    - blockinfile:
        path: /etc/hosts
        block: |
          127.0.0.1 {{adresse_rocketchat}}

- name: Démarrage du service rocket.chat
  hosts: all
  tags:
    - copie-docker-compose.yml
  tasks:
    - name: copie du docker-compose 
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: ~/docker-compose.yml
    - name: build et démarrage du dockercompose
      ansible.builtin.shell: docker-compose up -d
