# playbook pour l'initialisation d'un serveur
#   - installe un draveur


- hosts: initialisation
  become: true
  gather_facts: "{{ do_gather_facts | default(false) }}"
  vars_files:
    - draveurs.yml

  tasks:

    - name: Met à jour l'index des packages
      apt:
        update_cache: true

    - name: "Installe le draveur {{ user }}"
      include_role:
        name: draveurs
      vars:
        username: "{{ user }}"

    - name: "Supprime l'utilisateur {{ item }}"
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ delusers.split(',') | list }}"
