- hosts: "{{ owner | default(lookup('env', 'USER')) }}"
  become: true
  gather_facts: "{{ do_gather_facts | default(false) }}"
  vars_files:
    - draveurs.yml

  tasks:

    - name: Met à jour l'index des packages
      apt:
        update_cache: true

    - name: "Installe le draveur {{ user | default(ansible_user) }}"
      include_role:
        name: draveurs
      vars:
        username: "{{ user | default(ansible_user) }}"

    - name: "Supprime l'utilisateur {{ item }}"
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ delusers.split(',') | list }}"
      when: delusers is defined
