- hosts: owned_nodes
  name: Assure la configuration de base
  become: true
  vars_files:
    - draveurs.yml
    - nodes.yml
  tasks:

    - name: "Le draveur {{ item }} administre le système"
      include_role:
        name: draveurs
      vars:
        username: "{{ item }}"
      loop: "{{ draveurs }}"
      tags:
        - users

    - name: Le serveur est sécurisé
      include_role:
        name: endurcissement

    - name: Le serveur se connecte au réseau des draveurs
      include_role:
        name: reseau_drave
      vars:
        node: "{{ inventory_hostname }}"
