- hosts: "{{ owner | default(lookup('env', 'USER')) }}"
  name: Assure la configuration de base
  become: true
  gather_facts: false
  vars_files:
    - draveurs.yml

  tasks:
    - name: inclusion secrets
      include_vars:
        file: 'vault/{{inventory_hostname_short}}.yml'
      tags: always

    - name: 'Chaque draveur administre le système'
      include_role:
        name: draveurs
      vars:
        username: '{{ item }}'
      loop: '{{ draveurs }}'
      tags:
        - users

    - name: Le serveur est sécurisé
      include_role:
        name: endurcissement
        apply:
          tags: endurcissement
      tags: always

    - name: L'IP dynamique est configurée
      include_role:
        name: inadyn
        apply:
          tags: inadyn
      tags: always
      when: dyndns

    - name: VPNcloud est installé
      include_role:
        name: vpncloud
        apply:
          tags: vpncloud
      tags: always

    - name: Générer clé privée et publique vpncloud
      include_role:
        name: genkey
        apply:
          tags: [vpncloud, genkey]
      tags: always

    - name: Le serveur se connecte au réseau des draveurs
      include_role:
        name: reseau_drave
        apply:
          tags: reseau_drave
      tags: always
      vars:
        node: '{{ inventory_hostname }}'

    - name: MAJ fichier /etc/hosts
      include_role:
        name: hosts
        apply:
          tags: hosts
      tags: always

    - name: installe microk8s
      include_role:
        name: microk8s
        apply:
          tags: microk8s
      tags: always

    - name: ajoute fait
      include_role:
        name: microk8s_facts
        apply:
          tags: grappe
      tags: always

    - name: joint à la grappe
      when: clustered is defined and not clustered
      include_role:
        name: grappe
        apply:
          tags: grappe
      tags: always

    # - name: Test l'installation
    #   include_role:
    #     name: test
    #     apply:
    #       tags: test
    #   tags: always
