- hosts: owned_nodes
  name: Assure la configuration de base
  become: true
  gather_facts: true
  vars_files:
    - draveurs.yml
    - nodes.yml
  tasks:

    - name: "Le draveur {{ item }} administre le système"
      include_role:
        name: draveurs
      vars:
        username: "{{ item }}"
      loop: "{{ draveurs }}"
      tags:
        - users

    - name: Le serveur est sécurisé
      include_role:
        name: endurcissement
        apply:
          tags: endurcissement
      tags: always

    - name: VPNcloud est installé
      include_role:
        name: vpncloud
        apply:
          tags: vpncloud
      tags: always

    - name: Générer clé privée et publique vpncloud
      include_role:
        name: genkey
        apply:
          tags: [vpncloud, genkey]
      tags: [always, genkey]

    - name: Le serveur se connecte au réseau des draveurs
      include_role:
        name: reseau_drave
        apply:
          tags: reseau_drave
      tags: always
      vars:
        node: "{{ inventory_hostname }}"
