# Playbook qui installe Starship, un fancy shell
# Voir:  https://starship.rs/fr-FR/config/

- name: Installation de starship
  hosts: cribe # À modifier...
  tags:
    - starship
  become: 'True'
  tasks:
    - name: Téléchargement du script d'installation de starship
      get_url:
        url: https://starship.rs/install.sh
        dest: ~/starship.sh
    - name: Démarrage du script d'installation de starship
      ansible.builtin.command:
        cmd: bash ~/starship.sh -f
    - name: Vérification si starship est installé
      stat:
        path: /usr/local/bin/starship
      register: present
    - name: Effacement du script d'installation
      ignore_errors: true
      file:
        state: absent
        path: ~/starship.sh
      when: present.stat.exists
    - name: Vérification (et modification si nécessaire) du fichier /etc/skel/.bashrc
      lineinfile:
        dest: /etc/skel/.bashrc
        line: eval "$(starship init bash)"
        state: present
    - name: Copie du répertoire /etc/skel/.config/
      ansible.builtin.copy:
        src: ./files/.config/ # À vous de créer ce fichier (.gitignore)
        dest: /etc/skel/.config/
