---
- name: lit clées publiques
  become: no
  loop: "{{ groups['all'] }}"
  local_action:
    module: shell cat public/{{item}}.key
  when: "'public/{{ item }}.key' is exists"
  register: vpncloud_public_keys

- name: "Lit clée privée de {{inventory_hostname_short}}"
  become: no
  local_action:
    module: shell cat private/{{inventory_hostname_short}}.key
  register: vpncloud_private_key

- name: "Lit clée publique de {{inventory_hostname_short}}"
  become: no
  local_action:
    module: shell cat public/{{inventory_hostname_short}}.key
  register: vpncloud_public_key

- set_fact:
    vpncloud_private_key: "{{ vpncloud_private_key.stdout }}"

- set_fact:
    vpncloud_public_key: "{{ vpncloud_public_key.stdout }}"

- set_fact:
    vpncloud_public_keys: "{{ vpncloud_public_keys.results | json_query('[].stdout') }}"

- name: Écrit le fichier de configuration du réseau vpn
  template:
    src: drave.net.j2
    dest: /etc/vpncloud/drave.net

- systemd:
    name: vpncloud@drave
    state: restarted
    enabled: yes

- name: Configure le pare-feu
  community.general.ufw:
    rule: allow
    to_port: "{{vpn_port}}"
    protocol: udp
    comment: "Autoriser les connexions entrantes sur le port vpncloud (UDP)"