---
- name: Récupère les informations de la nodes
  set_fact:
    node_info: "{{ nodes | selectattr('name','contains', node) | list |  json_query(\"[0]\") }}"

#- name: liste clées publiques
#  become: no
#  local_action:
#    module: find
#    paths: "public/"
#    patterns: "*.key"
#  register: vpncloud_public_key_files



- name: lit clées publiques
  become: no
  loop: "{{ nodes }}"
  local_action:
    module: shell cat public/{{item.name}}.key
  register: vpncloud_public_keys


- name: Lit clée privée
  become: no
  local_action:
    module: shell cat private/{{node_info.name}}.key
  register: vpncloud_private_key

- set_fact:
      vpncloud_private_key: "{{ vpncloud_private_key.stdout }}"


- set_fact:
    vpncloud_public_key: "{{ vpncloud_public_keys.results | selectattr('item.name', 'equalto', node) | list | first| json_query('stdout') }}"

- set_fact:
    vpncloud_public_keys: "{{ vpncloud_public_keys.results | json_query('[].stdout') }}"


- name: Écrit le fichier de configuration du réseau vpn
  template:
    src: drave.net.j2
    dest: /etc/vpncloud/drave.net

- systemd:
    name: vpncloud@drave
    state: restarted
    enabled: yes
