---
- name: installe inadyn
  snap:
    name: inadyn

- name: configure inadyn
  template:
    src: inadyn.conf.j2
    dest: /var/snap/inadyn/current/inadyn.conf
  register: config

- name: redémarrage si fichier changé
  ansible.builtin.systemd:
    state: restarted
    name: snap.inadyn.daemon
  when: config.changed

- name: s'assure que le service est démarré
  ansible.builtin.systemd:
    state: started
    name: snap.inadyn.daemon
  when: not config.changed

- name: s'assurer que le service démarre au redémarrage machine
  ansible.builtin.systemd:
    enabled: yes
    name: snap.inadyn.daemon