---
- name: Ajoute le repo contenant vpncloud
  copy:
    content: "deb https://repo.ddswd.de/deb stable main"
    dest: /etc/apt/sources.list.d/vpncloud.list

- name: Ajoute la clef gpg pour vpncloud au trousseau de Apt
  ansible.builtin.apt_key:
    url: https://repo.ddswd.de/deb/public.key
    state: present

- apt:
    update_cache: true

- apt:
    name: vpncloud
