---
- name: Allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

- name: rate limiting failed connections
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: allow openssh server
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow all access to tcp port 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
