scan_timeout = 1000

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "sur [$hostname](bold red) dans "
trim_at = ""
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
format = "[Durée:$duration]($style)"
min_time = 1
show_milliseconds = true
style = "dimmed"

[git_branch]
format = "en [$symbol$branch]($style) "
